baseURL: ""
title: "Eternity"
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: ''

params:
  image: /images/banner.png
  subtitle: "Rethinking light and photography. Photographer in Cape Town."
  copyright: All rights reserved.
  author: "John Love"
  dontShowSource: true
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:hi@example.com'
      landing: true  
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://twitter.com/orealmotionlink'
      landing: true  
    - icon: 'fab fa-youtube fa-lg'
      url: 'https://twitter.com/orealmotionlink'
      landing: true  
    - icon: 'fab fa-linkedin fa-lg'
      url: 'https://twitter.com/orealmotionlink'
      landing: true  

  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: ''
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1    
    - name: archive
      url: /tags/archive/
      weight: 2    
    - name: people
      url: /tags/people/
      weight: 3    
    - name: work
      url: /tags/work/
      weight: 4    
    - name: holo
      url: /tags/holo/
      weight: 5    
    - name: space
      url: /tags/space/
      weight: 6    
    - name: nature
      url: /tags/nature/
      weight: 7    
    - name: about
      url: /about/
      weight: 8    
    